### ISSUE TITLE
New front

### ISSUE THREAD

**Issue by xXxRisingTidexXx** [xXxRisingTidexXx/raions#12]
Клієнтура жалілася на недостатньо зрозумілий UI. Потрібно виправити:
 - Введення геолокації (додати вулиці й історичні місцевості);
 - Відображення карток (з горизонталки на вертикальну табличку);
 - Перекласти інтерфейс (повністю український)
 - Уточнити відображення адрес (Показувати все до номеру будинку включно)

**Comment by starfolll** [comment]
Так-то перевод деталей лучше сделать на беке

**Comment by xXxRisingTidexXx** [comment]
Без б, накинемо po-file.

**Comment by xXxRisingTidexXx** [comment]
Хух, начебто, фронт підправили в #19 , тож дану ішшю закриваємо.
