### ISSUE TITLE
Cross-browser capability

### ISSUE THREAD

**Issue by xXxRisingTidexXx** [xXxRisingTidexXx/raions#8]
На даний момент лише Хром підтримує коректну роботу raions. Інші браузери також варто включити в список програм, що надають вільний доступ до аплікухи без плаваючої верстки, або ж довести, що через ряд технічних обмежень дана фіча не є необхідною. Чекаю на палку дискусію:)

**Comment by starfolll** [comment]
meh

**Comment by xXxRisingTidexXx** [comment]
Хехе. Враховуючі останні обставини й ставлення замовника, думаю, без підтримки мозіли чи опери ріелтори спокійнесенько й далі куритимуть бамбук.
